version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: travellist
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel

    db:
        image: mysql:latest
        container_name: laravel-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: mr
            MYSQL_PASSWORD: mr
            MYSQL_USER: rifqi
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - laravel

    phpmyadmin:
        # Gunakan Image phpmyadmin
        image: phpmyadmin/phpmyadmin
        # Expose Port
        ports:
            # Gunakan Port 8081 Untuk Mengakses phpmyadmin
            - "8081:80"
        # Koneksikan Ke Network localapp
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
